domain_boxes = [[-5.0, 5.0], [-5.0, -4.0], [-5.0, -4.5]]
cfl = 0.25
num_interior_points = 10001
num_ghost_points = 3
stop_time = 10.0
out_every_0d = 10
out_every_1d = 100
checkpoint_every = 10000
out_dir = "data"
redirect_std = false
