domain_boxes = [[-5.0, 5.0], [-5.0, -4.0], [-5.0, -4.5]] # computational domain
cfl = 0.25
num_interior_points = 1001
num_ghost_points = 3
max_step = -1
stop_time = 10.0
out_every = 10
out_dir = "data"
mongwane = true
redirect_std = false
