domain_boxes = [[-5.0, 5.0], [-1.0, 1.0], [-0.5, 0.5]] # computational domain
cfl = 0.25
num_interior_points = 1001
num_ghost_points = 3
stop_time = 10.0
out_every = 10
checkpoint_every = 1000
out_dir = "data"
redirect_std = false
